language: node_js
node_js:
  - '12'

notifications:
  email:
    on_success: never
    on_failure: always

script: yarn build

deploy:
  provider: npm
  edge: true
  email: npm@jupiterone.io
  api_key:
    secure: "RNlguHatWfk39q69bMXbHjBZraxEpQdpGE0n1zOqUFnNCoTQJRQ87ODP9sGysMZBra1UXS0+0blJGMSktCtyE3QeupCi6cquDbT5t1FPbUkmRSdNB6vCHR4Rrjk2+MVOKMv4hpu4zyotTr0K6fjAusRCpv8aCxr6l9BohtkPawBYZvRZWGFhCnt96f1uMjtiV5ByIdvMNR1w3ha1mWj0OaaiVda5F/N3SrDvRNvjN8RtmrNjgZMmP76TedooRfYfsIOWysjzoC4+OvSnOMo4icO9SqYFOMFyRu7kyQYBG50HtlnPSe37zFKlnlmU+rqGHZySaxfWToqMvfqOMf5Wq1ZhPMovaFfMd5qxP+hSi6IBIHONmqfbiYne1Ccdpy+WCKyvPPInX74kP9bPGyAoZ6g3+4z5If+h/f6fda7Uj1djVfihGmK3Ta7kBN6dssiKz5lNABjuy5yQxtI0kXnWRthCCTjNCBVSYJ968DSQ7aohQ+aj+j16+CGHFWEIY3l5+CBRx9LdOiMZYC/gIVJJsrY+vqddAUsYPYzDGo2Sa2Mw1MeO9sZ/dnpGgywpJvndcKBjSry5v1xbMtPvPRGjXiGZVCdrsvF0OVUaROu9OxS2mQi5iq1CK/R+ylEv7bCCumMJdl5ionkQhVTECdxEowiUxsENO3Asj8uGHb5E/VA="
  skip_cleanup: true
  on:
    tags: true
    branch: master
    repo: JupiterOne/graph-airwatch
    node: '12'
