version: "3.7"

services:
  graph:
    image: tinkerpop/gremlin-server:3.4
    volumes:
      - ./node_modules/@jupiterone/jupiter-managed-integration-sdk/gremlin-client/conf:/etc/opt/
    command: /etc/opt/gremlin-server.yaml
    restart: unless-stopped
    ports:
      - "8182:8182"